Rails.application.routes.draw do
  get 'like/_likebutton'
  get 'deepfunction/_deepfunctionform'
  get 'comment/_commentsform'
  get 'function/_functionform'
  get 'design/_designform'
  root 'welcome#home'

  get 'welcome/home'
  get 'welcome/off_discussion'
  get 'welcome/agendas'
  get 'welcome/meetings'
  get 'welcome/chairmen'
  get 'welcome/contributions'
  get 'welcome/calendar'
  get 'welcome/events'
  get 'welcome/about'
  get 'welcome/rel_media'
  get 'welcome/financials'
  get 'welcome/votes'
  get 'welcome/debate'
  get 'welcome/donations'
  get 'welcome/developments'
  get 'welcome/miss_statement'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
